### ISSUE TITLE
error in super method explanation

### ISSUE THREAD

**Issue by iamtash** [learn-co-curriculum/fewpjs-oo-class-extension-and-inheritance-super#3]
the return value shown on line 36 in the first code snippet, `=> Dog { name: 'Spot', _owner: null, breed: 'Foxhound' }`should read `=> Dog { _name: 'Spot', _owner: null, breed: 'Foxhound' }` since the call to the parent constructor `super(name)` would execute `this._name = name`.

**Comment by sgharms** [comment]
Thanks!
