### ISSUE TITLE
Miswritten code example in line 22. 

### ISSUE THREAD

**Issue by bebofofum** [learn-co-curriculum/fewpjs-oo-class-extension-and-inheritance-super#4]
The example creates an instance of the dog class assigning it to a variable called Charlie. But then calls the variable using.

let charlie = new Dog('Charlie B. Barkin', 'Mutt');
 
dog.info;
// => 'Charlie B. Barkin is a Mutt'

dog.info would return a ReferenceError as dog is not defined. To accurately get the response shown you would need to call as 
charlie.info

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

Thanks for contributing to the Flatiron School curriculum 💙
